format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$character
"""

[character]
success_symbol = '[::](green)'
error_symbol = '[::](red)'

[directory]
format = "[$read_only]($read_only_style)[$path]($style) "
style = "cyan"
read_only = "ğŸ” "

[git_commit]
tag_symbol = ' ï’ '

[git_branch]
symbol = "ï˜ "
style = "blue"

[git_status]
style = "red"

[python]
symbol = "îˆµ "
format = '[${symbol}(\($virtualenv\) )]($style)'
style = "yellow"
